### ISSUE TITLE
StyleProcessor (Broccoli plugin) error does not indicate which PostCSS plugin failed

### ISSUE THREAD

**Issue by maxkwallace** [n1ru4l/ember-cli-css-preprocess#31]
I'm not sure if this is definitely an issue with ember-cli-css-preprocess, but after upgrading to Ember CLI 2.10.0, I can't build my app.

```
Build failed.
The Broccoli Plugin: [StyleProcessor] failed with:
Error: Cannot read property 'indexOf' of undefined
    at postcss.process.then.catch (/home/mkw/mc/mentorcollective-ember/ember/node_modules/ember-cli-css-preprocess/processors/postcss.js:55:26)

The broccoli plugin was instantiated at: 
    at StyleProcessor.Plugin (/home/mkw/mc/mentorcollective-ember/ember/node_modules/broccoli-plugin/index.js:7:31)
    at StyleProcessor.CachingWriter [as constructor] (/home/mkw/mc/mentorcollective-ember/ember/node_modules/ember-cli-css-preprocess/node_modules/broccoli-caching-writer/index.js:18:10)
    at new StyleProcessor (/home/mkw/mc/mentorcollective-ember/ember/node_modules/ember-cli-css-preprocess/style-processor.js:28:16)
    at StyleProcessorPlugin.toTree (/home/mkw/mc/mentorcollective-ember/ember/node_modules/ember-cli-css-preprocess/index.js:38:26)
    at /home/mkw/mc/mentorcollective-ember/ember/node_modules/ember-cli-preprocess-registry/preprocessors.js:180:26
    at Array.forEach (native)
    at processPlugins (/home/mkw/mc/mentorcollective-ember/ember/node_modules/ember-cli-preprocess-registry/preprocessors.js:178:11)
    at module.exports.preprocessCss (/home/mkw/mc/mentorcollective-ember/ember/node_modules/ember-cli-preprocess-registry/preprocessors.js:148:10)
    at EmberApp.styles (/home/mkw/mc/mentorcollective-ember/ember/node_modules/ember-cli/lib/broccoli/ember-app.js:1319:28)
    at EmberApp.toArray (/home/mkw/mc/mentorcollective-ember/ember/node_modules/ember-cli/lib/broccoli/ember-app.js:1647:10)
    at EmberApp.toTree (/home/mkw/mc/mentorcollective-ember/ember/node_modules/ember-cli/lib/broccoli/ember-app.js:1668:30)
    at module.exports (/home/mkw/mc/mentorcollective-ember/ember/ember-cli-build.js:89:14)
    at CoreObject.setupBroccoliBuilder (/home/mkw/mc/mentorcollective-ember/ember/node_modules/ember-cli/lib/models/builder.js:72:19)
    at CoreObject.init (/home/mkw/mc/mentorcollective-ember/ember/node_modules/ember-cli/lib/models/builder.js:52:10)
    at CoreObject.superWrapper [as init] (/home/mkw/mc/mentorcollective-ember/ember/node_modules/ember-cli/node_modules/core-object/lib/assign-properties.js:32:18)
    at CoreObject.Class (/home/mkw/mc/mentorcollective-ember/ember/node_modules/ember-cli/node_modules/core-object/core-object.js:32:33)
    at CoreObject.run (/home/mkw/mc/mentorcollective-ember/ember/node_modules/ember-cli/lib/tasks/build.js:15:19)
    at CoreObject.<anonymous> (/home/mkw/mc/mentorcollective-ember/ember/node_modules/ember-cli/lib/commands/test.js:164:27)
    at tryCatch (/home/mkw/mc/mentorcollective-ember/ember/node_modules/rsvp/dist/lib/rsvp/-internal.js:215:12)
    at invokeCallback (/home/mkw/mc/mentorcollective-ember/ember/node_modules/rsvp/dist/lib/rsvp/-internal.js:230:13)
    at /home/mkw/mc/mentorcollective-ember/ember/node_modules/rsvp/dist/lib/rsvp/then.js:29:16
    at flush (/home/mkw/mc/mentorcollective-ember/ember/node_modules/rsvp/dist/lib/rsvp/asap.js:85:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

Any ideas/hints on what might be the issue?

**Comment by maxkwallace** [comment]
After removing `ember-cli-css-preprocess` from my `package.json` the build completes successfully.

**Comment by maxkwallace** [comment]
After digging into this more, this appears to be an issue with the `stylelint` plugin. I was able to get the build and PostCSS processing to work after disabling `stylelint`.

This would have been easier to debug if StyleProcessor plugin threw a more informative error message with some info about the plugin causing the problem. I'm going to change the title of the issue to reflect that.

**Comment by n1ru4l** [comment]
I will try to investigate some time on this, the issue (- if there is any with this module) must be in the file processor/postcss.js.I just pipe all plugins straight into postcss, all occuring errors get catched and are forwarded to the ember-cli. Could you please make a repository for reproducing that problem?

**Comment by maxkwallace** [comment]
Hey @n1ru4l -- thanks for the reply! Work's been too busy recently so I don't have time to follow up on this. I'm going to close the issue.

I was hoping there was some way to see which PostCSS plugin threw the error (if there was an error) but from looking at the code https://github.com/n1ru4l/ember-cli-css-preprocess/blob/master/processors/postcss.js#L49 it looks like that may not be possible.
