### ISSUE TITLE
Not working with node-sass > 3

### ISSUE THREAD

**Issue by pichfl** [n1ru4l/ember-cli-css-preprocess#32]
```sh
Error: Processor node-sass (4.3.0) is not compatible. Required version: ^3.4.2
    at _loadModule (/Users/pichfl/Desktop/timepiece/node_modules/ember-cli-css-preprocess/load-processor.js:46:17)
    at _loadProcessor (/Users/pichfl/Desktop/timepiece/node_modules/ember-cli-css-preprocess/load-processor.js:71:50)
    at loadProcessor (/Users/pichfl/Desktop/timepiece/node_modules/ember-cli-css-preprocess/load-processor.js:81:9)
    at StyleProcessor.<anonymous> (/Users/pichfl/Desktop/timepiece/node_modules/ember-cli-css-preprocess/style-processor.js:62:23)
    at next (native)
    at onFulfilled (/Users/pichfl/Desktop/timepiece/node_modules/co/index.js:65:19)
```

node-sass 4.x should be fine API wise. I can file a pull request.

**Comment by n1ru4l** [comment]
Would be awesome!

**Comment by pichfl** [comment]
See #34
